### PR TITLE
Surgery fixes and tweaks

### PR DESCRIPTION
**Pull request by Tropica1Owl**
# Description

This PR changes 2 things:

1. Fixes a faulty if state that allowed people to do surgery on ANYTHING in the staton (including walls, doors, and even the nuke)
2. Makes surgery unordered, meaning you don't need to order everything perfectly anymore to successfully do surgery.

## Summary by CodeRabbit

- **New Features**
	- Transitioned to a new surgical procedure framework focusing on wound checks.
  
- **Bug Fixes**
	- Resolved issues with surgical actions by refining tool checks in patient procedures.
	- Fixed a logical condition to prevent operations on invalid patient states.

### CODE REVIEW

**Comment by Agustron24** [comment]
Waaaaait SURGERY IN SS14?.

How to join into the server

**Comment by Eagle-0** [comment]
> Waaaaait SURGERY INSIDE SS14 FORK?
> 
> How to join into the server

Message me on discord, I assume you're from SSMV

**Comment by Agustron24** [comment]
> Message me on discord, I assume you're from SSMV

You messaged me first already. lol

**Comment by Eagle-0** [comment]
Closing because this surgery system is getting removed. Sorry sigma.

**Pull request closed without merging**
